<?php

namespace Application\NotepadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteBlockRepository extends EntityRepository
{
}
