security:
    encoders:
        Application\NotepadBundle\Entity\User:
            algorithm: bcrypt


    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:      ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: ApplicationNotepadBundle:User}
            

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _user_login_page
            logout:
                path:   /logout/
                target: /
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/notes/*, roles: ROLE_USER }
        
