## YAML Template.
services:
    application_notepad.form.type.login:
        class: Application\NotepadBundle\Form\LoginType
        tags:
            - { name: form.type, alias: login_form }
            
    application_notepad.form.type.singup:
        class: Application\NotepadBundle\Form\SignupType
        tags:
            - { name: form.type, alias: signup }
            
    application_notepad.security.userprovider:
       class:        Application\NotepadBundle\Security\UserProvider
       arguments: [ @doctrine.orm.default_entity_manager ]
       
    application_notepad.security.service.registration:
       class:        Application\NotepadBundle\Security\RegistrationService
       arguments: [ @doctrine.orm.default_entity_manager ]   